[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "aqueduct"
version = "20230523"
dependencies = [
    "dask",
    "distributed",
    "hydra-core",
]

[project.optional-dependencies]
dev = ["isort", "black", "myst-parser", "nb-clean", "nose", "parquet-tools", "sphinx", "sphinx_rtd_theme"]

[tool.black]
line-length = 88
target-version = ['py311']

[project.scripts]


[tool.pytest.ini_options]
pythonpath = "src"