[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "aqueduct"
version = "20230523"
dependencies = [
    "dask",
    "distributed",
    "hydra-core",
    "omegaconf",
    "nbformat",
    "nbconvert",
    "jupyter_client",
]

[project.optional-dependencies]
dev = ["isort", "black", "furo", "myst-parser", "nb-clean", "parquet-tools", "sphinx"]

[tool.black]
line-length = 88
target-version = ['py311']

[project.scripts]


[tool.pytest.ini_options]
pythonpath = "src"